web:
  build: .
  links:
    - memcached
  ports: 
    - "8085:8081"
  command: ["uwsgi", "--http", ":8081", "/home/simplewms/app/uwsgi.ini"]

memcached:
  image: memcached
  ports:
    - "11211"
  command: ["memcached", "-m", "32"]
